const data = {
  stopName: 'Sörnäistenkatu',
  arrivalList: [
    {
      scheduledArrival: 68400,
      realtimeArrival: 68378,
      arrivalDelay: -22,
      scheduledDeparture: 68400,
      realtimeDeparture: 68378,
      departureDelay: -22,
      realtime: true,
      realtimeState: 'UPDATED',
      serviceDay: 1540936800,
      headsign: 'Kalasatama(M)',
    },
    {
      scheduledArrival: 68820,
      realtimeArrival: 68847,
      arrivalDelay: 27,
      scheduledDeparture: 68820,
      realtimeDeparture: 68847,
      departureDelay: 27,
      realtime: true,
      realtimeState: 'UPDATED',
      serviceDay: 1540936800,
      headsign: 'Rautatientori via Kalasatama(M)',
    },
    {
      scheduledArrival: 69660,
      realtimeArrival: 69619,
      arrivalDelay: -41,
      scheduledDeparture: 69660,
      realtimeDeparture: 69619,
      departureDelay: -41,
      realtime: true,
      realtimeState: 'UPDATED',
      serviceDay: 1540936800,
      headsign: 'Kalasatama(M)',
    },
    {
      scheduledArrival: 70020,
      realtimeArrival: 70020,
      arrivalDelay: 0,
      scheduledDeparture: 70020,
      realtimeDeparture: 70020,
      departureDelay: 0,
      realtime: false,
      realtimeState: 'SCHEDULED',
      serviceDay: 1540936800,
      headsign: 'Rautatientori via Kalasatama(M)',
    },
    {
      scheduledArrival: 70860,
      realtimeArrival: 70860,
      arrivalDelay: 0,
      scheduledDeparture: 70860,
      realtimeDeparture: 70860,
      departureDelay: 0,
      realtime: false,
      realtimeState: 'SCHEDULED',
      serviceDay: 1540936800,
      headsign: 'Kalasatama(M)',
    },
  ],
};

export default data;
